//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DatPhong
    {
        public int IDDP { get; set; }
        public int IDKH { get; set; }
        public Nullable<int> SONGUOI { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public Nullable<double> SOTIEN { get; set; }
        public Nullable<int> SONGAYO { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> DISABLED { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_BY { get; set; }
        public Nullable<bool> THEODOAN { get; set; }
        public string NOTE { get; set; }
    }
}
